
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Migara
 */
public class CurrentPrincipal extends javax.swing.JFrame {
    
    Connection con = null;
    Statement stmt  = null;
    ResultSet rs = null;

    /**
     * Creates new form CurrentPrincipal
     */
    public CurrentPrincipal() {
        initComponents();
         con = databaseConnection.connection();
        viewPrincipal();
    }

    public void viewPrincipal()
    {
        try
        {
            stmt = con.createStatement();
            
            String query = "SELECT * FROM principal WHERE pastpresent = 'PRESENT'";
            
            rs = stmt.executeQuery(query);
            
            while(rs.next())
            {
                name.setText(rs.getString("name"));
                address.setText(rs.getString("address"));
                age.setText(String.format("%s", rs.getInt("age")));
                birthday.setText(String.format("%tD", rs.getDate("birthday")));
                gender.setText(rs.getString("gender"));
                contact.setText(String.format("%s", rs.getInt("contact")));
                
                BufferedImage image = ImageIO.read(rs.getBinaryStream("image"));
                imageIcon.setIcon(new ImageIcon(image));
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        imageIcon = new javax.swing.JLabel();
        mainmenu = new javax.swing.JButton();
        editorAdd1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CURRENT PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 21, -1, -1));

        age.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        age.setForeground(new java.awt.Color(255, 0, 0));
        age.setText("AGE");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 424, 800, 60));

        name.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        name.setForeground(new java.awt.Color(255, 0, 0));
        name.setText("NAME");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 244, 800, 60));

        address.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        address.setForeground(new java.awt.Color(255, 0, 0));
        address.setText("ADDRESS");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 334, 800, 60));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel5.setText("CONTACT NO.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 694, 200, 60));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel6.setText("BIRTHDAY");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 514, 200, 60));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel7.setText("GENDER");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 604, 200, 60));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel8.setText("NAME");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 244, 200, 60));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel9.setText("ADDRESS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 334, 200, 60));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel10.setText("AGE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 416, 200, 60));

        birthday.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        birthday.setForeground(new java.awt.Color(255, 0, 0));
        birthday.setText("BIRTHDAY");
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 514, 800, 60));

        gender.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 0, 0));
        gender.setText("GENDER");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 604, 800, 60));

        contact.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 0, 0));
        contact.setText("CONTACT NO.");
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 694, 800, 60));
        jPanel1.add(imageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1473, 270, 303, 287));

        mainmenu.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        mainmenu.setForeground(new java.awt.Color(0, 0, 255));
        mainmenu.setText("MAIN MENU");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        jPanel1.add(mainmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1618, 37, -1, -1));

        editorAdd1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        editorAdd1.setForeground(new java.awt.Color(0, 0, 255));
        editorAdd1.setText("EDIT / ADD");
        editorAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorAdd1ActionPerformed(evt);
            }
        });
        jPanel1.add(editorAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 889, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HAND.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1536, 37, -1, 67));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EDIT.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 889, -1, 67));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/THEME 9.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1090));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editorAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorAdd1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Principal view = new Principal();
        view.setVisible(true);
    }//GEN-LAST:event_editorAdd1ActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home view = new Home();
        view.setVisible(true);
    }//GEN-LAST:event_mainmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel contact;
    private javax.swing.JButton editorAdd1;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel imageIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainmenu;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
